name: Publish Package to npmjs

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Set version to release version
        run: |
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version

      - name: Commit version bump
        env:
          CI_COMMIT_MESSAGE: Bump version to ${{ github.event.release.tag_name }}
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name '{{ env.CI_COMMIT_AUTHOR }}'  
          git config --global user.email 'Walledgarden@users.noreply.github.com'
          git add package.json
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push origin HEAD:main

      - name: Build
        run: npm run build

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
